name: Bug Report
description: Something isn't working as expected
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      Thank you for contributing to the Composable Architecture! 
      
      Before you submit your issue, please complete each text area below with the relevant details for your bug, and complete the steps in the checklist
- type: textarea
  attributes:
    label: Description
    description: |
      A short description of the incorrect behavior. 

      If you think this issue has been recently introduced and did not occur in an earlier version, please note that. If possible, include the last version that the behavior was correct in addition to your current version.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Checklist
    options:
    - label: If possible, I've reproduced the issue using the `main` branch of this package.
      required: false
    - label: This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues).
      required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: Describe what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Actual behavior
    description: Describe or copy/paste the behavior you observe.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: |
      Explanation of how to reproduce the incorrect behavior. 
      
      This could include an attached project or link to code that is exhibiting the issue, and screen recording.
    placeholder: "1. ...&#10;&#10;2. ...&#10;&#10;3. ...&#10;&#10;4. ..."
  validations:
    required: false
- type: input
  attributes:
    label: The Composable Architecture Version Information
    description: The version of the Composable Architecture used to reproduce this issue.
    placeholder: "'0.38.0' for example, or a commit hash"
- type: textarea
  attributes:
    label: Swift Compiler Version Information
    description: The version of Swift used to reproduce this issue. 
    placeholder: Output from 'xcrun swiftc --version'
    render: shell
